package com.codegence.aurora.game;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

/**
 * Created by lmorganti on 04/03/16.
 */
@DynamoDBTable(tableName = "cgGames")
@AllArgsConstructor
@NoArgsConstructor
public class Game {

    private String gameID;
    @Setter
    @NotEmpty
    private List<Faction> factions;
    @Setter
    private String urlMap;
    @Setter
    @NotEmpty
    private String victoryCondition;
    @Setter
    private String state;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getGameID() {
        return gameID;
    }

    @DynamoDBAttribute
    public List<Faction> getFactions() {
        return factions;
    }

    @DynamoDBAttribute
    public String getUrlMap() {
        return urlMap;
    }

    @DynamoDBAttribute
    public String getVictoryCondition() {
        return victoryCondition;
    }

    @DynamoDBAttribute
    public String getState() {
        return state;
    }

    @JsonIgnore
    public void setGameID(String gameID) {
        this.gameID = gameID;
    }

    @JsonIgnore
    public void setState(String state) {
        this.state = state;
    }
}

