google:
  client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope: email profile
  resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false



logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true



#AWS

amazon.accessKey: ${AMAZON_ACCESS_KEY}
amazon.secretKey: ${AMAZON_SECRET_KEY}
amazon.sqs.name.genesis: cg-sector-genesis
amazon.sqs.name.apocalipse: cg-sector-apocalipse