google:
  client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope: profile email
  resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false



logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true



#dynamodb
amazon.dynamodb.endpoint: https://dynamodb.us-east-1.amazonaws.com
amazon.dynamodb.accessKey: ${AMAZON_DYNAMODB_ACCESSKEY}
amazon.dynamodb.secretKey: ${AMAZON_DYNAMODB_SECRETKEY}