package com.codegence.aurora.server;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * Created by lmorganti on 19/02/16.
 */
@DynamoDBTable(tableName = "cgServers")
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Server {
    private String serverID;
    private String playerID;
    private String nickName;
    private String url;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getServerID() {
        return serverID;
    }

    @DynamoDBAttribute
    public String getNickName() {
        return nickName;
    }

    @DynamoDBAttribute
    @JsonIgnore
    public String getPlayerID() {
        return playerID;
    }

    @DynamoDBAttribute
    public String getUrl() {
        return url;
    }
}
