package com.codegence.aurora.player;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Created by lmorganti on 18/02/16.
 */
@DynamoDBTable(tableName = "cgPlayers")

@AllArgsConstructor
@NoArgsConstructor
public class Player {

    private String playerID;
    @Setter
    @NotEmpty
    private String nickName;

    private String googleID;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getPlayerID() {
        return playerID;
    }

    @DynamoDBAttribute
    public String getNickName() {
        return nickName;
    }

    @DynamoDBAttribute
    public String getGoogleID() {
        return googleID;
    }

    @JsonIgnore
    public void setPlayerID(String playerID) {
        this.playerID = playerID;
    }

    @JsonIgnore
    public void setGoogleID(String googleID) {
        this.googleID = googleID;
    }
}
